# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
	config.vm.box = "centos/stream8"
	config.vm.define "server" do |server|
		server.vm.hostname = "server.loc"
		server.vm.network "private_network", ip: "192.168.57.10"
	end
        config.vm.provision "ansible" do |ansible|
           	ansible.playbook = "conf.yml"
           	ansible.become = "true"
        end 
end
